package:
  name: conda-forge-build-setup
  version: 1.1.0

build:
  number: 0
  script:
    - if not exist "%LIBRARY_BIN%" mkdir "%LIBRARY_BIN%"                                                                 # [win]
    - mkdir -p "${PREFIX}/bin"                                                                                           # [unix]
    - COPY "%RECIPE_DIR%\\run_conda_forge_build_setup_win" "%LIBRARY_BIN%\\run_conda_forge_build_setup.bat"              # [win]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_osx" "${PREFIX}/bin/run_conda_forge_build_setup"                     # [osx]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_linux" "${PREFIX}/bin/run_conda_forge_build_setup"                   # [linux]

requirements:
  run:
    - conda-build         # [linux]
    - conda-build 1.20.0  # [osx]
    - conda-build 1.20.0  # [win64 and py34]
    - conda-build         # [win and not (win64 and py34)]
    - jinja2
    - anaconda-client

test: {}

about:
  home: https://github.com/conda-forge/conda-forge-build-setup-feedstock
  summary: A package installed by conda-forge each time a build is run on CI. This package has side-effects to your conda config.
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
