package:
  name: conda-forge-build-setup
  version: 1.1.0

build:
  number: 0
  script:
    - IF NOT EXIST %PREFIX%\etc\conda\activate.d MKDIR %PREFIX%\etc\conda\activate.d  # [win]
    - COPY %RECIPE_DIR%\activate.bat %PREFIX%\etc\conda\activate.d\conda-forge-build-setup_activate.bat  # [win]
    - mkdir -p "${PREFIX}/etc/conda/activate.d"  # [unix]
    - cp "${RECIPE_DIR}/activate.sh" "${PREFIX}/etc/conda/activate.d/conda-forge-build-setup_activate.sh"  # [unix]

requirements:
  run:
    - conda-build         # [linux]
    - conda-build 1.20.0  # [osx]
    - conda-build 1.20.0  # [win64 and py34]
    - conda-build         # [win and not (win64 and py34)]
    - jinja2
    - anaconda-client

test: {}

about:
  home: https://github.com/conda-forge/conda-forge-build-setup-feedstock
  summary: A package installed by conda-forge each time a build is run on CI. This package has side-effects to your conda config.
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
