# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "D1ZSq6vdkjuDXW+MWSPR3A7mmp5ASwA1HGHRjpG5GA/FxoK012XWTWeQW6qcVDTPGEkAXdAtrxdkg9Fn7s7C2efxfMZvLdH4F+nBuqCiTzBFqAwwkL0CeP2rMfZc8mo5fPpnaoZMA4zKm6ssyO1XUPhzlv0WKQOdBe3h04fXQZGF4ar630e4LDVUgfE5HMFUivxpm09AW9QJ53n4AaCcpW379Qa8IGaO3g53IZN4JqtZ8sXvDkCDHPnEZUAgzS+pgq4DS7Gj2T79o1PfZwpLuSwPVO9cAtRFQ5EfAIPH9oUFuW9TNYtX3ruRSuPl6cjCp7jG9XoggGae5VMElUDwtTlfJadOaHQJNlxQUN0WZBPSetitdcVc2IGDNS4aFBSWhBGh/FdrMSRqv7dvdLreLCBTQ8AWz9tW/IB6LvfqngdaWSNGLb4Ntbft1yWx1t5d9TlsLmpWL0MBIbg16vd2Yccfe4out85aSa9UyZXsvVoEmsoeOJ+XvonYLHB2PfC90miSIGElLWt1ncoUASIZ1iv86iTnamFnaKCq2T4XebllDOVeQ7iASvZmDfs5om23VNZqVBtEx2MUz4bHGOH/gnqkxXwHdVsX1N7NYJwO7g03dJW/xGlKR+UxCsa9C8Bx48ubsvhn/u/VXnc68mN20DCMNHptQQts5MVUEZNocAU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      conda install --yes conda-build=1
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
