travis:
  secure:
    BINSTAR_TOKEN: D1ZSq6vdkjuDXW+MWSPR3A7mmp5ASwA1HGHRjpG5GA/FxoK012XWTWeQW6qcVDTPGEkAXdAtrxdkg9Fn7s7C2efxfMZvLdH4F+nBuqCiTzBFqAwwkL0CeP2rMfZc8mo5fPpnaoZMA4zKm6ssyO1XUPhzlv0WKQOdBe3h04fXQZGF4ar630e4LDVUgfE5HMFUivxpm09AW9QJ53n4AaCcpW379Qa8IGaO3g53IZN4JqtZ8sXvDkCDHPnEZUAgzS+pgq4DS7Gj2T79o1PfZwpLuSwPVO9cAtRFQ5EfAIPH9oUFuW9TNYtX3ruRSuPl6cjCp7jG9XoggGae5VMElUDwtTlfJadOaHQJNlxQUN0WZBPSetitdcVc2IGDNS4aFBSWhBGh/FdrMSRqv7dvdLreLCBTQ8AWz9tW/IB6LvfqngdaWSNGLb4Ntbft1yWx1t5d9TlsLmpWL0MBIbg16vd2Yccfe4out85aSa9UyZXsvVoEmsoeOJ+XvonYLHB2PfC90miSIGElLWt1ncoUASIZ1iv86iTnamFnaKCq2T4XebllDOVeQ7iASvZmDfs5om23VNZqVBtEx2MUz4bHGOH/gnqkxXwHdVsX1N7NYJwO7g03dJW/xGlKR+UxCsa9C8Bx48ubsvhn/u/VXnc68mN20DCMNHptQQts5MVUEZNocAU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
