travis:
  secure:
    BINSTAR_TOKEN: Oef6y6m9iOnV4EB4Haz4OikGLttmi38XBckojbl2W0vD+QmJr+wLOs6//MO8twbOcwue9CMft61k7WeEcTG/mo3BgLDaSzBlhBvjMwi0ZgwNx+lvd62zlY8wBEx1Z0PaGdFQXZIDOJa3CIBE/crnhWyzC7oQHCP9DPM0sscrIYELsIOzLfhc1+rbY1sYXT58tuyhGionjtmMb9iCak01eAuZn50K7H6dqzV+IJGcLAGzM8Lllr6qhYZv9yvo96gGISowTUwqvMK1IGEJWuiZQ82Q9D1OVgHL8jHsiiNTW9kkrPu1hV0KCxu6C78O0nGlzt//LSwqysQ7BNvokWHV+vYLHIgkBihAF7QW0hkKDwU5+dl/rL60otiD++TN4QzSXw6sg3Gn5SwyXLwSaMBEhK7aIcx3jkcvdb6iex78XXt+NiYXi3grpYomo8KEq9TaYJLJMpMvDTcPQjYJBE+F3y+7FK6P5To0A1j0EChmq2YPxWbaH2CA4maviTfjzMezmV0tNclql0gkULIndE4X2BX/yltGpj0MAJC0q5f6lrik6d5XzS0Wojs9JEhlKU6rVQ2VwT5Q5m9Vxo/xmIKneuxFfqQWIxmTTJmfI479SUQes2+k6UE9tWqrDiYZON25T1ehddA9IKJpzUxdhgbYfw0UhbiAHTjiHtCK5vnSVSM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
